version: '3.7'

services:
  development_jwt:
    build:
      context: .
      dockerfile: Dockerfile.build
    image: development_jwt:latest
    container_name: development_jwt
    volumes:
      - ".:/jwt"
    ports:
      - "5000:5000"

  test_jwt:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: test_jwt:latest
    container_name: test_jwt
    volumes:
      - ".:/jwt"
    ports:
      - "8081:8081"
    depends_on: 
      - development_jwt