FROM python:3.7

ENV FLASK_APP=api.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update -y
EXPOSE 5000

COPY . /jwt/app
WORKDIR /jwt/app

CMD ["flask","run"]